"""Tests for calibration v2 (revision Task 5.2): per-model ECE/AUROC with
message-clustered bootstrap CIs, and DerSimonian-Laird random-effects
meta-analysis across models.

All tests run on SIMULATED / hand-built fixtures, never on the real
labeled parquet (still being generated by a background job at the time
this task was implemented -- see the task brief's environment note).
"""
import numpy as np
import pandas as pd
import pytest

from idrift.analysis.calibration_v2 import (
    build_calibration_frame,
    ece,
    meta_analyze,
    per_model_calibration,
)

# ---------------------------------------------------------------------------
# 1. ECE on a rigged perfectly-calibrated set.
# ---------------------------------------------------------------------------


def test_ece_near_zero_on_perfectly_calibrated_set():
    # 10 confidence levels, each with exactly enough correct/incorrect
    # draws that the empirical accuracy in that bin equals the stated
    # confidence -- e.g. conf=0.3 -> 3/10 correct, conf=0.7 -> 7/10 correct.
    rng = np.random.default_rng(0)
    conf = []
    correct = []
    for level in np.arange(0.05, 1.0, 0.1):  # bin midpoints: .05,.15,...,.95
        n = 100
        n_correct = int(round(level * n))
        block = np.array([1] * n_correct + [0] * (n - n_correct))
        rng.shuffle(block)
        conf.extend([level] * n)
        correct.extend(block.tolist())
    conf = np.array(conf)
    correct = np.array(correct)

    result = ece(conf, correct, n_bins=10, scheme="equal_width")
    assert result < 0.02


def test_ece_rejects_out_of_range_confidence():
    conf = np.array([0.1, 0.5, 1.5])  # 1.5 is out of [0, 1] -- e.g. an
    # un-normalized 0-100 verbalized confidence slipping through.
    correct = np.array([1, 0, 1])
    with pytest.raises(ValueError, match=r"\[0, ?1\]"):
        ece(conf, correct)


def test_ece_rejects_negative_confidence():
    conf = np.array([-0.1, 0.5])
    correct = np.array([1, 0])
    with pytest.raises(ValueError, match=r"\[0, ?1\]"):
        ece(conf, correct)


# ---------------------------------------------------------------------------
# 2. Both binning schemes work on a skewed-confidence fixture.
# ---------------------------------------------------------------------------


def test_both_binning_schemes_supported_on_skewed_fixture():
    rng = np.random.default_rng(1)
    # Skewed: most confidences bunched near 0.9-1.0, a few near 0.
    conf = np.concatenate(
        [rng.uniform(0.9, 1.0, size=180), rng.uniform(0.0, 0.2, size=20)]
    )
    correct = rng.binomial(1, conf)

    e_width = ece(conf, correct, n_bins=10, scheme="equal_width")
    e_freq = ece(conf, correct, n_bins=10, scheme="equal_frequency")

    for value in (e_width, e_freq):
        assert np.isfinite(value)
        assert 0.0 <= value <= 1.0

    with pytest.raises(ValueError, match="scheme"):
        ece(conf, correct, n_bins=10, scheme="not_a_real_scheme")


# ---------------------------------------------------------------------------
# 3. Message-clustered bootstrap CI is WIDER than a naive iid bootstrap on
#    data with strong within-message correlation (the load-bearing gate).
# ---------------------------------------------------------------------------


def _build_clustered_fixture(seed, n_messages=30, n_replicates=8):
    """Build a fixture where correctness/confidence are essentially
    constant WITHIN a message but vary strongly ACROSS messages -- the
    textbook case where a message-clustered bootstrap must report more
    uncertainty than a naive iid bootstrap over all rows (an iid bootstrap
    treats every one of the many correlated replicate rows within a message
    as an independent unit, so it drastically understates how few truly
    independent "clusters" (messages) actually informed the estimate)."""
    rng = np.random.default_rng(seed)
    rows = []
    for mi in range(n_messages):
        # Each message gets its OWN confidence level and its OWN
        # correctness propensity -- shared by every replicate of that
        # message (the within-message correlation).
        msg_conf = rng.uniform(0.05, 0.95)
        msg_is_correct = 1 if rng.random() < msg_conf else 0
        for rep in range(n_replicates):
            rows.append(
                {
                    "message_id": f"m{mi:03d}",
                    "model": "modelA",
                    "confidence": msg_conf,
                    "correct": msg_is_correct,
                }
            )
    return pd.DataFrame(rows)


def _naive_iid_bootstrap_ece_width(df, n_boot, seed, n_bins=10, scheme="equal_width"):
    rng = np.random.default_rng(seed)
    conf = df["confidence"].to_numpy(dtype=float)
    correct = df["correct"].to_numpy(dtype=float)
    n = len(df)
    draws = np.empty(n_boot)
    for b in range(n_boot):
        idx = rng.integers(0, n, size=n)
        draws[b] = ece(conf[idx], correct[idx], n_bins=n_bins, scheme=scheme)
    lo, hi = np.percentile(draws, [2.5, 97.5])
    return float(hi - lo)


def test_message_clustered_bootstrap_ci_wider_than_naive_iid():
    df = _build_clustered_fixture(seed=42)

    result = per_model_calibration(df, n_boot=1000, seed=7)
    stats = result["modelA"]
    clustered_lo, clustered_hi = stats["ece_ci"]
    clustered_width = clustered_hi - clustered_lo

    naive_width = _naive_iid_bootstrap_ece_width(df, n_boot=1000, seed=7)

    assert clustered_width > naive_width


# ---------------------------------------------------------------------------
# 4. per_model_calibration: shape, AUROC one-class guard, comparability
#    caveat, determinism.
# ---------------------------------------------------------------------------


def _two_model_fixture(seed=3, n_messages=25, n_replicates=4):
    rng = np.random.default_rng(seed)
    rows = []
    for model, bias in (("modelA", 0.0), ("modelB", 0.15)):
        for mi in range(n_messages):
            for rep in range(n_replicates):
                conf = float(np.clip(rng.uniform(0.05, 0.95) + bias, 0.0, 1.0))
                is_correct = int(rng.random() < conf)
                rows.append(
                    {
                        "message_id": f"{model}_m{mi:03d}",
                        "model": model,
                        "confidence": conf,
                        "correct": is_correct,
                    }
                )
    return pd.DataFrame(rows)


def test_per_model_calibration_shape_and_caveat():
    df = _two_model_fixture()
    result = per_model_calibration(df, n_boot=200, seed=1)

    assert set(result.keys()) == {"modelA", "modelB"}
    for model, stats in result.items():
        assert set(stats.keys()) == {
            "ece",
            "ece_ci",
            "auroc",
            "auroc_ci",
            "n",
            "n_messages",
            "notes",
        }
        assert 0.0 <= stats["ece"] <= 1.0
        assert len(stats["ece_ci"]) == 2
        assert stats["ece_ci"][0] <= stats["ece_ci"][1]
        assert stats["n"] == n_replicates_total(df, model)
        assert stats["n_messages"] == df[df["model"] == model]["message_id"].nunique()
        assert "not" in stats["notes"].lower() or "comparable" in stats["notes"].lower()


def n_replicates_total(df, model):
    return int((df["model"] == model).sum())


def test_auroc_one_class_guard_never_crashes():
    # Every row correct=1 -> AUROC is undefined (single class).
    df = pd.DataFrame(
        {
            "message_id": [f"m{i}" for i in range(20)],
            "model": ["modelA"] * 20,
            "confidence": np.linspace(0.1, 0.9, 20),
            "correct": [1] * 20,
        }
    )
    result = per_model_calibration(df, n_boot=50, seed=0)
    stats = result["modelA"]
    assert stats["auroc"] is None
    assert stats["auroc_ci"] is None
    assert "auroc" in stats["notes"].lower() or "undefined" in stats["notes"].lower()


def test_per_model_calibration_determinism():
    df = _two_model_fixture()
    result_a = per_model_calibration(df, n_boot=300, seed=5)
    result_b = per_model_calibration(df, n_boot=300, seed=5)

    for model in result_a:
        assert result_a[model]["ece"] == result_b[model]["ece"]
        assert result_a[model]["ece_ci"] == result_b[model]["ece_ci"]
        assert result_a[model]["auroc"] == result_b[model]["auroc"]
        assert result_a[model]["auroc_ci"] == result_b[model]["auroc_ci"]


# ---------------------------------------------------------------------------
# 5. meta_analyze: DerSimonian-Laird pooling.
# ---------------------------------------------------------------------------


def _homogeneous_per_model_stats(true_mean=0.10, se=0.02, k=6):
    # All models report (near-)identical ECE point estimates and CI widths
    # -- no true between-model heterogeneity, so tau2 should be ~0 and the
    # pooled estimate should recover true_mean closely.
    stats = {}
    for i in range(k):
        stats[f"model{i}"] = {
            "ece": true_mean,
            "ece_ci": [true_mean - 1.96 * se, true_mean + 1.96 * se],
        }
    return stats


def _heterogeneous_per_model_stats():
    # Point estimates spread far apart relative to their (tight) CIs --
    # real between-model heterogeneity that a fixed-effect pool would
    # understate the uncertainty of.
    values = [0.02, 0.05, 0.30, 0.35, 0.08, 0.40]
    se = 0.01
    stats = {}
    for i, v in enumerate(values):
        stats[f"model{i}"] = {
            "ece": v,
            "ece_ci": [v - 1.96 * se, v + 1.96 * se],
        }
    return stats


def test_meta_analyze_recovers_known_pooled_mean_on_homogeneous_inputs():
    stats = _homogeneous_per_model_stats(true_mean=0.10, se=0.02, k=6)
    result = meta_analyze(stats, metric="ece")

    assert set(result.keys()) == {"pooled", "ci", "tau2", "q", "i2", "k_models", "caveat"}
    assert result["k_models"] == 6
    assert abs(result["pooled"] - 0.10) < 0.01
    assert result["tau2"] == pytest.approx(0.0, abs=1e-6)
    assert result["ci"][0] <= result["pooled"] <= result["ci"][1]


def test_meta_analyze_tau2_positive_on_heterogeneous_inputs():
    stats = _heterogeneous_per_model_stats()
    result = meta_analyze(stats, metric="ece")

    assert result["tau2"] > 0
    assert result["i2"] > 0
    assert result["k_models"] == 6


def test_meta_analyze_carries_comparability_caveat():
    stats = _homogeneous_per_model_stats()
    result = meta_analyze(stats, metric="ece")
    assert isinstance(result["caveat"], str) and len(result["caveat"]) > 0


def test_meta_analyze_skips_models_with_none_metric():
    stats = _homogeneous_per_model_stats(k=4)
    stats["model_no_auroc"] = {"ece": 0.1, "ece_ci": [0.05, 0.15], "auroc": None, "auroc_ci": None}
    result = meta_analyze(stats, metric="auroc")
    # No model has a usable AUROC point estimate -> nothing to pool.
    assert result["k_models"] == 0
    assert result["pooled"] is None


# ---------------------------------------------------------------------------
# 6. build_calibration_frame -- hand-built frame only, never the real parquet.
# ---------------------------------------------------------------------------


def test_build_calibration_frame_derives_correct_and_rescales_confidence(tmp_path):
    raw = pd.DataFrame(
        {
            "message_id": ["m1", "m1", "m2", "m3"],
            "model": ["gemma3:27b", "gemma3:27b", "qwen3:8b", "gemma3:27b"],
            "label": ["faithful", "drift", "degraded", "faithful"],
            "confidence": [90.0, 40.0, 60.0, 100.0],
        }
    )
    path = tmp_path / "labeled_fixture.parquet"
    raw.to_parquet(path)

    out = build_calibration_frame(str(path))

    assert list(out["correct"]) == [True, False, False, True]
    assert out["confidence"].tolist() == pytest.approx([0.9, 0.4, 0.6, 1.0])
    # Original columns survive untouched.
    assert out["message_id"].tolist() == raw["message_id"].tolist()
    assert out["model"].tolist() == raw["model"].tolist()


def test_build_calibration_frame_output_is_valid_ece_input(tmp_path):
    raw = pd.DataFrame(
        {
            "message_id": ["m1", "m2", "m3", "m4"],
            "model": ["gemma3:27b"] * 4,
            "label": ["faithful", "faithful", "drift", "degraded"],
            "confidence": [80.0, 60.0, 30.0, 50.0],
        }
    )
    path = tmp_path / "labeled_fixture2.parquet"
    raw.to_parquet(path)

    out = build_calibration_frame(str(path))
    value = ece(out["confidence"].to_numpy(), out["correct"].to_numpy().astype(float), n_bins=4)
    assert np.isfinite(value)


# ---------------------------------------------------------------------------
# 7. Final-review must-fix #1: NaN verbalized confidence (119 of 533,400 rows
#    in the real labeled cohort) must be dropped + reported by
#    build_calibration_frame, and the metric layer must fail loud (not
#    silently) if a NaN ever bypasses that drop.
# ---------------------------------------------------------------------------


def test_build_calibration_frame_drops_and_reports_nan_confidence(tmp_path):
    raw = pd.DataFrame(
        {
            "message_id": ["m1", "m2", "m3", "m4", "m5"],
            "model": ["gemma3:27b", "gemma3:27b", "qwen3:8b", "gemma3:27b", "qwen3:8b"],
            "label": ["faithful", "drift", "degraded", "faithful", "faithful"],
            # Rows 2 and 5 (index 1, 4) have a missing verbalized confidence.
            "confidence": [90.0, np.nan, 60.0, 100.0, np.nan],
        }
    )
    path = tmp_path / "labeled_fixture_nan.parquet"
    raw.to_parquet(path)

    out = build_calibration_frame(str(path))

    # The 2 NaN-confidence rows are dropped.
    assert len(out) == 3
    assert not out["confidence"].isna().any()
    # The dropped count is reported via .attrs and matches exactly.
    assert out.attrs["dropped_nan_confidence"] == 2
    # Surviving rows are unaffected (same values, in original relative order).
    assert out["message_id"].tolist() == ["m1", "m3", "m4"]
    assert out["confidence"].tolist() == pytest.approx([0.9, 0.6, 1.0])
    assert list(out["correct"]) == [True, False, True]


def test_check_conf_range_raises_on_nan_naming_count():
    conf = np.array([0.1, np.nan, 0.5, np.nan, 0.9])
    correct = np.array([1, 0, 1, 0, 1], dtype=float)
    with pytest.raises(ValueError, match="2"):
        ece(conf, correct)


def test_clean_frame_passes_through_build_and_per_model_calibration_unchanged(tmp_path):
    raw = pd.DataFrame(
        {
            "message_id": ["m1", "m2", "m3", "m4"],
            "model": ["gemma3:27b"] * 4,
            "label": ["faithful", "faithful", "drift", "degraded"],
            "confidence": [80.0, 60.0, 30.0, 50.0],
        }
    )
    path = tmp_path / "labeled_fixture_clean.parquet"
    raw.to_parquet(path)

    out = build_calibration_frame(str(path))

    # No rows dropped on a clean (no-NaN) frame -- the guard does not
    # false-trigger.
    assert out.attrs["dropped_nan_confidence"] == 0
    assert len(out) == len(raw)
    assert out["confidence"].tolist() == pytest.approx((raw["confidence"] / 100.0).tolist())

    # per_model_calibration runs to completion, untouched, on the clean
    # frame produced by build_calibration_frame.
    result = per_model_calibration(out, n_boot=50, seed=0)
    assert set(result.keys()) == {"gemma3:27b"}
    assert np.isfinite(result["gemma3:27b"]["ece"])
