"""Tests for the cross-classified one-vs-rest mixed model on realized
message-level corruption (revision Task 5.1).

All tests run on SIMULATED data built here, never on the real labeled/
exposure parquets (still being generated by a background job at the time
this task was implemented -- see the task brief's environment note).
"""
import numpy as np
import pandas as pd
import pytest

from idrift.analysis.mixed_models import build_analysis_frame, fit_multinomial

# ---------------------------------------------------------------------------
# Simulation ingredients for the headline recovery gate.
#
# 40 messages x 5-level CER grid x 3 replicates = 600 rows. Drift-vs-rest
# probability is generated from a KNOWN logistic model:
#
#   logit(P(drift)) = beta0 + beta_cer * realized_cer + 0.02 * n_errors
#                     + 0.001 * char_len + 0.3 * corrupted_negation
#                     + 0.3 * corrupted_numeral + fam_effect + msg_re[message]
#
# with beta_cer = 4.0 (KNOWN positive slope, the primary quantity under
# test), msg_re ~ N(0, SD_MSG_TRUE = 0.8) (KNOWN message-level random-
# intercept SD, the second quantity under test), and a fixed +/-0.4 shift
# between the two simulated model families. Non-drift rows are split
# faithful/degraded by an independent coin flip (irrelevant to the fitted
# model, just needed so all three one-vs-rest outcomes have some support).
#
# SIM_SEED=6 is a fixed constant (not tuned per test run): across a sweep of
# seeds 0-7 during development, seed 6 gave a representative recovery
# (drift-vs-rest realized_cer point estimate 4.11 against true 4.0, message
# SD point estimate 0.76 against true 0.8) rather than a best-case outlier,
# while every seed in that sweep passed the same coverage/sign assertions
# below.
# ---------------------------------------------------------------------------

SIM_SEED = 6
BETA0_TRUE = -2.2
BETA_CER_TRUE = 4.0
SD_MSG_TRUE = 0.8
N_MESSAGES = 40
CER_LEVELS = (0.0, 0.1, 0.2, 0.3, 0.4)
N_REP = 3
MODELS = ("gemma3:4b", "gemma3:27b", "qwen3:8b", "qwen3:32b")
CORPORA = ("AUTH", "CRIT")
_FAMILY_EFFECT = {"gemma3": -0.4, "qwen3": 0.4}


def _simulate(seed):
    rng = np.random.default_rng(seed)
    msg_re = rng.normal(0, SD_MSG_TRUE, N_MESSAGES)
    rows = []
    for mi in range(N_MESSAGES):
        message_id = f"msg_{mi:03d}"
        corpus = CORPORA[mi % 2]
        for cer in CER_LEVELS:
            for rep in range(N_REP):
                model_id = MODELS[rng.integers(len(MODELS))]
                family = model_id.split(":")[0]
                n_errors = int(rng.poisson(1 + 8 * cer))
                char_len = int(rng.integers(20, 120))
                corrupted_negation = int(rng.random() < 0.1)
                corrupted_numeral = int(rng.random() < 0.1)
                lin = (
                    BETA0_TRUE
                    + BETA_CER_TRUE * cer
                    + 0.02 * n_errors
                    + 0.001 * char_len
                    + 0.3 * corrupted_negation
                    + 0.3 * corrupted_numeral
                    + _FAMILY_EFFECT[family]
                    + msg_re[mi]
                )
                p_drift = 1 / (1 + np.exp(-lin))
                is_drift = rng.binomial(1, p_drift)
                if is_drift:
                    label = "drift"
                else:
                    label = "faithful" if rng.random() < 0.8 else "degraded"
                rows.append(
                    dict(
                        message_id=message_id,
                        replicate_idx=rep,
                        realized_cer=cer,
                        n_errors=n_errors,
                        char_len=char_len,
                        corrupted_negation=corrupted_negation,
                        corrupted_numeral=corrupted_numeral,
                        model_id=model_id,
                        family=family,
                        corpus=corpus,
                        label=label,
                    )
                )
    return pd.DataFrame(rows)


@pytest.fixture(scope="module")
def sim_df():
    return _simulate(SIM_SEED)


# ---------------------------------------------------------------------------
# 1. Simulated recovery (the gate).
# ---------------------------------------------------------------------------


def test_drift_slope_recovery_and_engine_documented(sim_df):
    result = fit_multinomial(sim_df, seed=0)

    assert set(result.keys()) == {"faithful", "degraded", "drift"}
    drift = result["drift"]
    assert drift["outcome"] == "drift"
    assert drift["engine"] in ("glmm_vb", "clustered_logit_fallback")
    assert drift["n_obs"] == len(sim_df)
    assert drift["n_groups"]["message_id"] == N_MESSAGES

    coef = drift["coefficients"]["realized_cer"]
    # (a) correct sign and CI coverage of the known true slope, regardless
    # of which engine fired.
    assert coef["est"] > 0
    assert coef["ci_lo"] <= BETA_CER_TRUE <= coef["ci_hi"]

    # (b) message-level variance component: only asserted for the primary
    # VB engine (the fallback explicitly reports variance components as
    # unavailable -- see its "notes" -- so there is nothing to recover
    # there; if the fallback fires in this environment, (a) above is the
    # full gate and that is expected/documented, not a test bug).
    if drift["engine"] == "glmm_vb":
        assert drift["converged"] is True
        msg_sd_est = drift["variance_components"]["message_id"]
        assert abs(msg_sd_est - SD_MSG_TRUE) < 0.4
    else:
        assert drift["variance_components"] == {}
        assert "unavailable" in drift["notes"]


def test_fallback_ladder_fires_when_primary_engine_raises(sim_df, monkeypatch):
    # The chosen SIM_SEED converges via the primary VB engine in this
    # environment (see test_drift_slope_recovery_and_engine_documented), so
    # the fallback ladder is never exercised end to end by that test alone.
    # Force the primary engine to fail here (independent of any real
    # numerical non-convergence) to verify the ladder itself: `notes` names
    # the fallback, `engine` reports it, and coefficients/CIs still come
    # back usable, with variance_components explicitly empty.
    import idrift.analysis.mixed_models as mm

    def _boom(data, seed):
        raise RuntimeError("forced failure for fallback-ladder test")

    monkeypatch.setattr(mm, "_fit_vb", _boom)
    result = fit_multinomial(sim_df, seed=0)

    drift = result["drift"]
    assert drift["engine"] == "clustered_logit_fallback"
    assert drift["variance_components"] == {}
    assert "FALLBACK LADDER FIRED" in drift["notes"]
    assert "forced failure for fallback-ladder test" in drift["notes"]
    coef = drift["coefficients"]["realized_cer"]
    assert coef["est"] > 0
    assert coef["ci_lo"] <= BETA_CER_TRUE <= coef["ci_hi"]


def test_degraded_and_faithful_fits_run_without_crashing(sim_df):
    result = fit_multinomial(sim_df, seed=0)
    for outcome in ("degraded", "faithful"):
        r = result[outcome]
        assert r["outcome"] == outcome
        assert r["engine"] in ("glmm_vb", "clustered_logit_fallback")
        assert "realized_cer" in r["coefficients"]
        assert np.isfinite(r["coefficients"]["realized_cer"]["est"])


# ---------------------------------------------------------------------------
# 2. Determinism.
# ---------------------------------------------------------------------------


def test_determinism_same_df_and_seed_reproduce_identical_coefficients(sim_df):
    result_a = fit_multinomial(sim_df, seed=0)
    result_b = fit_multinomial(sim_df, seed=0)

    assert result_a["drift"]["engine"] == result_b["drift"]["engine"]
    for outcome in ("faithful", "degraded", "drift"):
        ca = result_a[outcome]["coefficients"]
        cb = result_b[outcome]["coefficients"]
        assert ca.keys() == cb.keys()
        for name in ca:
            assert ca[name]["est"] == cb[name]["est"]
            assert ca[name]["se"] == cb[name]["se"]
        assert result_a[outcome]["variance_components"] == result_b[outcome]["variance_components"]


def test_invalid_label_value_raises():
    bad = pd.DataFrame(
        {
            "label": ["not_a_real_label"],
            "realized_cer": [0.1],
            "n_errors": [1],
            "char_len": [10],
            "corrupted_negation": [0],
            "corrupted_numeral": [0],
            "message_id": ["m0"],
            "replicate_idx": [0],
            "model_id": ["gemma3:4b"],
            "family": ["gemma3"],
            "corpus": ["AUTH"],
        }
    )
    with pytest.raises(ValueError, match="CLASS_ORDER"):
        fit_multinomial(bad)


def test_missing_required_column_raises(sim_df):
    dropped = sim_df.drop(columns=["char_len"])
    with pytest.raises(ValueError, match="char_len"):
        fit_multinomial(dropped)


def test_unmatched_join_nan_row_raises_with_row_count(sim_df):
    # Simulates exactly the real failure mode: an unmatched labeled row from
    # `build_analysis_frame`'s LEFT join leaves NaN in a model column
    # (revision Task 5.1 review). Without the guard, patsy's default
    # `missing='drop'` would silently drop this one row inside the fit while
    # `n_obs` (captured before fitting) still counted it, and the clustered
    # fallback's `cov_kwds={"groups": data["message_id"]}` (built at full,
    # pre-drop length) would raise its own unrelated `ValueError`.
    contaminated = sim_df.copy()
    contaminated.loc[contaminated.index[0], "realized_cer"] = np.nan

    with pytest.raises(ValueError, match=r"1 row\(s\)"):
        fit_multinomial(contaminated)


def test_unmatched_join_nan_rows_count_multiple(sim_df):
    contaminated = sim_df.copy()
    contaminated.loc[contaminated.index[:3], "n_errors"] = np.nan

    with pytest.raises(ValueError, match=r"3 row\(s\)"):
        fit_multinomial(contaminated)


def test_clean_fully_matched_frame_reports_honest_n_obs(sim_df):
    # Guard must not false-trigger on a clean (fully-matched) frame: n_obs
    # should equal the frame length exactly, i.e. no row was silently
    # dropped by patsy before the count was taken.
    assert not sim_df.isna().any().any()  # sanity: the shared fixture is clean
    result = fit_multinomial(sim_df, seed=0)
    for outcome in ("faithful", "degraded", "drift"):
        assert result[outcome]["n_obs"] == len(sim_df)
        assert result[outcome]["engine"] in ("glmm_vb", "clustered_logit_fallback")


# ---------------------------------------------------------------------------
# 3. build_analysis_frame join correctness (hand-built fixtures only).
# ---------------------------------------------------------------------------


def _labeled_fixture():
    return pd.DataFrame(
        {
            "message_id": ["m1", "m1", "m2", "m3"],
            "cer_target": [0.1, 0.2, 0.1, 0.1],
            "replicate_idx": [0, 0, 0, 0],
            "label": ["drift", "faithful", "degraded", "faithful"],
            "realized_cer": [0.09, 0.21, 0.11, 0.10],
            "model": ["gemma3:27b", "gemma3:27b", "qwen3:8b", "gemma3:27b"],
            "corpus": ["AUTH", "AUTH", "CRIT", "AUTH"],
        }
    )


def _exposure_fixture():
    # m3/cer_target=0.1/replicate_idx=0 deliberately has NO matching exposure
    # row, so the unmatched-labeled-row path is exercised for real.
    return pd.DataFrame(
        {
            "message_id": ["m1", "m1", "m2"],
            "corpus": ["AUTH", "AUTH", "CRIT"],
            "cer_target": [0.1, 0.2, 0.1],
            "replicate_idx": [0, 0, 0],
            "n_errors": [3, 5, 1],
            "corrupted_negation": [1, 0, 0],
            "corrupted_numeral": [0, 0, 1],
            "text": ["HELLO WORLD", "HELLO WORLD", "GOOD MORNING TO YOU"],
        }
    )


def test_build_analysis_frame_join_correctness_and_derivations():
    merged = build_analysis_frame(_labeled_fixture(), _exposure_fixture())

    # No row multiplication: exactly one output row per labeled input row.
    assert len(merged) == 4

    # Right predictor values land on the right rows (m1/cer=0.1 vs m1/cer=0.2
    # must not be swapped or averaged).
    row_m1_a = merged[(merged.message_id == "m1") & (merged.cer_target == 0.1)].iloc[0]
    row_m1_b = merged[(merged.message_id == "m1") & (merged.cer_target == 0.2)].iloc[0]
    row_m2 = merged[merged.message_id == "m2"].iloc[0]
    assert row_m1_a["n_errors"] == 3
    assert row_m1_a["corrupted_negation"] == 1
    assert row_m1_b["n_errors"] == 5
    assert row_m1_b["corrupted_negation"] == 0
    assert row_m2["n_errors"] == 1
    assert row_m2["corrupted_numeral"] == 1

    # char_len derived from exposure's `text` length (no literal char_len
    # column in the fixture).
    assert row_m1_a["char_len"] == len("HELLO WORLD")
    assert row_m2["char_len"] == len("GOOD MORNING TO YOU")

    # model -> model_id rename, family derived by stripping the ":size" tag.
    assert row_m1_a["model_id"] == "gemma3:27b"
    assert row_m1_a["family"] == "gemma3"
    assert row_m2["model_id"] == "qwen3:8b"
    assert row_m2["family"] == "qwen3"

    # labeled's own corpus survives untouched (no _x/_y collision column).
    assert row_m2["corpus"] == "CRIT"
    assert "corpus_x" not in merged.columns and "corpus_y" not in merged.columns

    # Unmatched handling is explicit: m3 has no exposure match -> NaN
    # attached columns, row still present (not dropped).
    row_m3 = merged[merged.message_id == "m3"].iloc[0]
    assert pd.isna(row_m3["n_errors"])
    assert pd.isna(row_m3["char_len"])
    assert row_m3["label"] == "faithful"  # labeled-side data untouched


def test_build_analysis_frame_respects_existing_char_len_column():
    exposure = _exposure_fixture()
    exposure["char_len"] = [999, 999, 999]  # literal column should win, not be recomputed
    merged = build_analysis_frame(_labeled_fixture(), exposure)
    assert (merged.loc[merged.message_id != "m3", "char_len"] == 999).all()


def test_build_analysis_frame_raises_on_missing_join_key():
    labeled = _labeled_fixture().drop(columns=["cer_target"])
    with pytest.raises(ValueError, match="join key"):
        build_analysis_frame(labeled, _exposure_fixture())
